import pandas as pd
dashboard_df = pd.DataFrame({
    'dashboard': [
        'migration-population',
        'gold-reserves',
        'google-serp',
        'twitterdash',
        'trending-twitter',
        'us-baby-names',
        'advertools',
        'boxofficemojo',
        'health-spending',
        'life-exp',
        'massacres',
        'median-age-world',
        'migration-by-country',
        'mothersday-map',
        'pop-growth',
        'terrorism',
        'robotstxt',
        '',
    ],
    'title': [
        'Migration and Population Density - WorldBank Data',
        'Gold Reserves per Country & Quarter - IMF Data',
        '🔎 Search Engine Results Pages - Google SERP Dashboard',
        'Twitter Dashboard - Text Analysis & Mining - Twitter API',
        'Trending on Twitter Now, Anywhere - Twitter Dashboard',
        '🇺🇸👶 US Baby Names Data & Trends',
        'Generate SEM Keywords for AdWords Campaigns',
        '🎥 BoxofficeMojo Dashboard Alltime Data',
        'Healthcare Spending 2014 - CIA Factbook',
        'Life Expectancy 2017 - CIA Factbook',
        'World Massacres',
        'Median Age 2017 - CIA Factbook',
        'Migration Stats 2017 - CIA Factbook',
        'Mothers Day Celebrations',
        'Population Growth 2017 - CIA Factbook',
        'Global Terrorism Database',
        '🤖 robots.txt Tester for Large Scale Testing',
        'Dashboardom',
    ],
    'h1': [
        'Migration Stats by Country and Year',
        'Gold Reserves per Country & Quarter',
        '🔎 Search Engine Results Pages - Google',
        'Search and Analyze Twitter, Create a Dataset',
        'Trending on Twitter Now, Anywhere',
        '🇺🇸👶 US Baby Names',
        'SEM Keyword Generator',
        '🎥 BoxofficeMojo Dashboard Alltime Data',
        'Healthcare Spending 2014 - CIA Factbook',
        'Life Expectancy 2017 - CIA Factbook',
        'World Massacres',
        'Median Age 2017 - CIA Factbook',
        'Migration Stats 2017 - CIA Factbook',
        'Mothers Day Celebrations',
        'Population Growth 2017 - CIA Factbook',
        'Global Terrorism Database',
        '🤖 robots.txt Tester for Large Scale Testing',
        'Dashboardom',
    ],
    'h2': [
        'Visualize changes in population density and migration',
        'Analyze changes in official gold reserves - IMF Data',
        'Get SERPs for multiple keywords and parameters, in one DataFrame',
        'Search Twitter & generate a filterable downloadable dataset of tweets',
        'Trending hashtags and topics on Twitter - all locations',
        'Annual births by name in the US 1910 - 2016',
        'Generate keywords for your campaigns on a massive scale',
        'BoxofficeMojo domestic box-office data all-time',
        'Healthcare spending by country in 2014',
        'Life expectancy per country in 2017',
        'Wikipedia\'s list of events named massacres',
        'Median age and age distribution by country in 2017',
        'Net migration by country in 2017',
        'Mothers day celebrations in the world',
        'Population growth per country in 2017',
        'World terrorist attacks during 1970 - 2016',
        'For a given robots.txt file check which URLs can be fetched for all user-agents in the file',
        'This website!',
    ],
    'data': [
        'WorldBank',
        'International Monetary Fund',
        'Google Custom Search Engine',
        'Twitter API',
        'Twitter API',
        'Social Security Agency',
        'https://github.com/eliasdabbas/advertools',
        'BoxofficeMojo',
        'CIA World Factbook',
        'CIA World Factbook',
        'Wikipedia',
        'CIA World Factbook',
        'CIA World Factbook',
        'Wikipedia',
        'CIA World Factbook',
        'START Consortium',
        'advertools robotstxt module',
        ' ',
    ],
    'data_link': [
        'https://data.worldbank.org/',
        'https://data.imf.org/',
        'https://developers.google.com/custom-search/v1/cse/list',
        'https://developer.twitter.com',
        'https://developer.twitter.com',
        'https://www.ssa.gov/oact/babynames/',
        'NA',
        'http://www.boxofficemojo.com/alltime/domestic.htm',
        'https://www.cia.gov/library/publications/the-world-factbook/fields/2225.html',
        'https://www.cia.gov/library/publications/the-world-factbook/fields/2102.html',
        'https://en.wikipedia.org/wiki/List_of_events_named_massacres',
        'https://www.cia.gov/library/publications/the-world-factbook/fields/2010.html',
        'https://www.cia.gov/library/publications/the-world-factbook/fields/2112.html',
        'https://en.wikipedia.org/wiki/Mother%27s_Day',
        'https://www.cia.gov/library/publications/the-world-factbook/fields/2002.html',
        'https://www.kaggle.com/START-UMD/gtd',
        'https://advertools.readthedocs.io/en/master/advertools.robotstxt.html',
        ' ',
    ],
    'tags': [
        'population, migration, world',
        'gold, economics, IMF, central banks',
        'google, SEO, search engine optimization, keywords',
        'twitter, social media, text mining',
        'twitter, social media',
        'population, statistics, data-viz, names, USA',
        'advertising, PPC, marketing, adwords, bingads, SEM, keywords',
        'movies, hollywood, box-office',
        'healthcare, world, cia-factbook',
        'population, age, world, cia-factbook',
        'terrorism, massacres, wikipedia, world',
        'population, age, world, cia-factbook',
        'migration, world, cia-factbook',
        'world, mothers, wikipedia',
        'population, world, cia-factbook',
        'terrorism, world',
        'google, SEO, robots.txt, search engine optimization',
        'tools, website',
    ],
    'git_repo': [
        'https://github.com/eliasdabbas/migration-population',
        'https://github.com/eliasdabbas/gold-reserves',
        'https://github.com/eliasdabbas/google-serp',
        'https://github.com/eliasdabbas/twitterdash',
        'https://github.com/eliasdabbas/trending-twitter',
        'https://github.com/eliasdabbas/baby_names',
        'https://github.com/eliasdabbas/advertools_app',
        'https://github.com/eliasdabbas/boxofficemojo',
        'https://github.com/eliasdabbas/health_spending',
        'https://github.com/eliasdabbas/life_expectancy',
        'https://github.com/eliasdabbas/wikipedia_list_of_massacres',
        'https://github.com/eliasdabbas/median_age_dashboard',
        'https://github.com/eliasdabbas/migration_dashboard',
        'https://github.com/eliasdabbas/mothers_day',
        'https://github.com/eliasdabbas/population_growth',
        'https://github.com/eliasdabbas/terrorism',
        'https://github.com/eliasdabbas/robotstxt_app',
        'https://github.com/eliasdabbas/dashboardom'
    ],
    'height': [
        '1336px',
        '1561px',
        '1338px',
        '1735px',
        '850px',
        '750px',
        '793px',
        '2500px',
        '800px',
        '1500px',
        '1600px',
        '1000px',
        '1300px',
        '800px',
        '1500px',
        '2360px',
        '980px',
        '800px',
    ]
})

dashboard_df.to_csv('data/dashboards_df.csv', index=False)